tools:
    external_code_coverage: true
build:
    image: default-bionic
    environment:
        php: 8.4.12
        apt_packages:
            - libssl-dev
            - pkg-config
            - build-essential
            - zlib1g-dev
    nodes:
        analysis:
            tests:
                override:
                    - php-scrutinizer-run
filter:
    paths:
        - src/*