tools:
    external_code_coverage: true
build:
    image: default-bionic
    environment:
        php: 8.4.12
    nodes:
        analysis:
            tests:
                override:
                    - php-scrutinizer-run
filter:
    paths:
        - src/*